name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy_prod:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: "Build"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ secrets.WORKDIR }}
            bash ./config/ci/git-update.sh
            bash ./config/ci/git-tag.sh
            bash ./config/ci/deploy.prod.sh
